export const LIGHT_PARAM = {
  LIGHT_HEIGHT: 30,
  LIGHT_ROW: 6,
  LIGHT_COL: 6,
  ROW_DISTANCE: 12,
  COL_DISTANCE: 24,
};
export const TABLE_SIZE = {
  PLAY_FIELD_H: 28.4,
  PLAY_FIELD_W: 14.2,
  POCKET_SIZE: 1.17,
  TOP_RAILS_W: 1.27,
  CUSHIONS_W: 0.51,
  Z_PARAM: 0.4,
};
export const BALL_SIZE = 0.57;
